### ISSUE TITLE
Crash when opening f3 menu on 1.16.1

### ISSUE THREAD

**Issue by EvilDeaaaadd** [cominixo/BetterF3#1]
Tried removing all mods but BetterF3 and ModMenu, still happens. It seems to work if I remove all modules and add them back but breaks again after game restarts.

Crash report:
[crash-2020-08-12_16.39.36-client.txt](https://github.com/cominixo/BetterF3/files/5063043/crash-2020-08-12_16.39.36-client.txt)

**Comment by cominixo** [comment]
Thanks for reporting this, I couldn't exactly reproduce this but I'm pretty sure what was causing it. I published a new release here on GitHub, I'd appreciate it if you could check if the crash still happens on that version.

**Comment by EvilDeaaaadd** [comment]
No longer crashes, thank you!
