### ISSUE TITLE
[Bug]: if you add this mod, that makes disappear xyz location

### ISSUE THREAD

**Issue by anan1122** [cominixo/BetterF3#105]
### Describe the Bug

unfortunately when I add this file on mods folder, when I press f3, I can't find xyz, when I off this mod, same. and I deleted mod and same. 
I had to reinstall minecraft, then finally I can see xyz
I tried forge and fabric but it was same...

### Steps to Reproduce

.

### Expected Behavior

.

### Modloader Type

Fabric

### Modloader Version

43.1.2

### Mod Version

1.3.2

**Comment by TreyRuffy** [comment]
Once you open the game, click F3 + M and add the coordinates module to the left side.
