### ISSUE TITLE
[Bug]: Bug with modules

### ISSUE THREAD

**Issue by Pepito727** [cominixo/BetterF3#107]
### Describe the Bug

when I try to change the mod settings, I delete the coordinates section, now I don't know how to make it come back

### Steps to Reproduce

make a button to reset the configurations or to make modules come back

### Expected Behavior

idk

### Screenshots

![Captura de pantalla (103)](https://user-images.githubusercontent.com/112661619/188006581-79ef80bf-7023-47a2-b687-41d719765890.png)

No coordinates

### Modloader Type

Fabric

### Modloader Version

0.14.9 1.19

### Mod Version

1.3.2

**Comment by TreyRuffy** [comment]
Under the F3 + M menu, if you choose the left side, you can add the coordinates module back and rearrange it into the correct location.
