### ISSUE TITLE
[Feature]: Day count

### ISSUE THREAD

**Issue by TheFlameNinja26** [cominixo/BetterF3#108]
### Describe the Request

There should be a day count like in vanilla minecraft to show the amount of days on either the server or in a singleplayer world

### Modloader Version

1.19.2

**Comment by TreyRuffy** [comment]
I believe this already exists. It is under "Days Played" and works on both singleplayer and multiplayer.

**Comment by TheFlameNinja26** [comment]
Thanks for that :) I will have a look soon
