### ISSUE TITLE
[Bug]: modules are not shown in the 'Add Module' menu

### ISSUE THREAD

**Issue by rocamocha** [cominixo/BetterF3#109]
### Describe the Bug

It appears that the modules do not exist in the menu where you would add modules to the GUI.

### Steps to Reproduce

Delete a module and then try to add it back in using 'Add Module'
The only available option is 'Separator'

### Expected Behavior

To be able to add a deleted module back into the list of enabled modules.

### Screenshots

![image](https://user-images.githubusercontent.com/30216269/190088755-e7717d28-fec1-4ffd-8992-ad0a7096be23.png)

### Modloader Type

Fabric

### Modloader Version

0.14.9

### Mod Version

1.3.2

**Comment by TreyRuffy** [comment]
I see where the confusion comes from. When on that screen, it autofills with the separator module because it is the most common module to add. Simply delete the autofilled text and replace it with the module you would like to add.
