### ISSUE TITLE
[Bug]: Help text wrong with RebindAllTheKeys

### ISSUE THREAD

**Issue by Fabian42** [cominixo/BetterF3#111]
### Describe the Bug

If the [RebindAllTheKeys mod](https://www.curseforge.com/minecraft/mc-mods/rebindallthekeys) is installed, I can rebind F3+Q to something else. With BetterF3, the help text will still tell me to press F3+Q.

### Modloader Type

Fabric

### Modloader Version

1.19.2

### Mod Version

1.4.0

**Comment by TreyRuffy** [comment]
I think the best way to fix this would be to open the jar file with an archive extractor and manually modify the `text.betterf3.line.help_press` value.
