### ISSUE TITLE
[Bug]: Can't readd modules after deletion

### ISSUE THREAD

**Issue by blueonthemoon** [cominixo/BetterF3#112]
### Describe the Bug

After deleting some of the base modules to customize the menu, I am unable to add back any of the deleted modules. The only module I can add to either side is the 'separator' one. Searching for a module manually yields no results.

### Steps to Reproduce

Delete a module with text on either side. Try and add back that same module in the 'add' menu. For me, it is unavailable, only showing separator modules.

### Expected Behavior

I expected the list of addable modules to include stuff beyond the separators.

### Screenshots

![image](https://user-images.githubusercontent.com/115184828/194396721-458d3dd1-1fe6-473c-b25c-ce9741b4929f.png)

### Modloader Type

Fabric

### Modloader Version

1.19.2

### Mod Version

1.19.2

### Additional Context

This bug persists in the main menu or in-game and attempts to delete/reinstall or otherwise 'reset' the mod has led nowhere.

**Comment by TreyRuffy** [comment]
While you can add the modules, it prefills with separator. To add another module, you must delete the text. I can fix this soon though.

**Comment by blueonthemoon** [comment]
Thank you so much. Such an obvious thing I didn't even think to try.
