### ISSUE TITLE
[Bug]: F3 edit doesnt let me readd the back things to it (Fabric 4.0.0 1.19/1/2 22w42a)

### ISSUE THREAD

**Issue by PopSikle23** [cominixo/BetterF3#120]
### Describe the Bug

if i delete a module i cant re add said module 

### Steps to Reproduce

delete module and suffer because you cant readd it

### Expected Behavior

i should be able to  re add it

### Screenshots

![2022-11-07_00 26 46](https://user-images.githubusercontent.com/88212115/200232853-3d8abfe1-fce9-4476-9f79-443fcc50dd2f.png)

### Modloader Type

Fabric

### Modloader Version

0.14.10

### Mod Version

4.0.0

**Comment by TreyRuffy** [comment]
Backspace until the word `separator` is gone to see the rest of the modules.
