### ISSUE TITLE
[Bug] Mod settings fail to write to config file

### ISSUE THREAD

**Issue by ghost** [cominixo/BetterF3#121]
This bug started occurring yesterday, for seemingly no reason. I noticed that my F3 menu was a bit different than usual, so i went to the settings to change it. Upon trying to save the settings, my game crashed. It would appear that it is unable to read or write to and from the betterf3.json file anymore. This started happening while betterf3.json still exists, and was perfectly accessible. None of the file permissions have changed, and i even tried it in a new installation with updated versions of the mods and fabric to see if that would fix the issue. It did not.

Crash log from first instance: [crash-2022-11-07_16.17.20-client.txt](https://github.com/cominixo/BetterF3/files/9962665/crash-2022-11-07_16.17.20-client.txt)

Crash log from clean install: [crash-2022-11-08_07.15.06-client.txt](https://github.com/cominixo/BetterF3/files/9962671/crash-2022-11-08_07.15.06-client.txt)

I highly doubt its a file perms issue, since other mods or able to read and write just fine.

**Comment by TreyRuffy** [comment]
I haven't seen this error before and I haven't had a chance to fully read through it, but is the `config` directory's permissions setup properly too? If the directory doesn't exist, try creating it. 

I'll be able to check on it further soon.

**Comment by ghost** [comment]
I've never had to mess around with the file perms before. Like i said, other mods can read and write to their config files just fine. It's an issue specific to this mod. I had been using the 1.4.0 version of the mod for a long while, and suddenly it stopped working, even though nothing changed (at least not that i can see) on my end.

If it is an issue with permissions, then why can other mods read and write to the same directory while this mod can't? It just makes no sense to me.

**Comment by TreyRuffy** [comment]
Have you tried to delete the config file? There was possibly a corrupted save. What launcher are you using too?

**Comment by ghost** [comment]
I'm using the default launcher. I did try deleting betterf3.json, but that didn't matter. It never created a new file, and when i created a new file for it, it never wrote to that file.

**Comment by ghost** [comment]
I have recently decided to put the mod back into my normal installation. This time however, the game can't even launch without crashing.

[crash-2022-11-19_01.54.27-client.txt](https://github.com/cominixo/BetterF3/files/10046666/crash-2022-11-19_01.54.27-client.txt)

I honestly have no idea what is going on.

Update:
I've installed the same mods with the same fabric version in a custom MultiMC instance, and i can now adjust the settings and play the game as normal. The only difference with this instance, is that i used the Java runtime environment installed on my system, and not the one bundled with MC normally. Perhaps my installation was just borked in such a way that prevented this mod specifically from working properly. I'll be closing this issue now, since i understand that it seems to be a one-off case with my installation.
