### ISSUE TITLE
[Bug]: Not much f3 information.

### ISSUE THREAD

**Issue by ghost** [cominixo/BetterF3#130]
### Describe the Bug

So i am not getting as much f3 info as in the images. Not sure if its another mod i have or what.

### Steps to Reproduce

I dont know

### Expected Behavior

I am expecting to see some more debug information than this

### Screenshots

![2023-01-11_18 14 18](https://user-images.githubusercontent.com/97406208/211885569-a99d66f9-d8ae-4cb6-a786-eec52c4af39b.png)

### Modloader Type

Fabric

### Modloader Version

quilt 0.17.8

### Mod Version

BetterF3-5.1.0-Fabric-1.19.3

### Additional Context

MOD LIST(as produced by a simple batch program):
08/01/2023  18:22        78,577,890 AmbientSounds_FABRIC_v5.2.15_mc1.19.3.jar
08/01/2023  18:26         1,057,584 appleskin-fabric-mc1.19.3-2.4.2.jar
08/01/2023  19:11         1,743,279 BetterF3-5.1.0-Fabric-1.19.3.jar
08/01/2023  18:26            60,639 CameraOverhaul-1.4.0-fabric-universal.jar
11/01/2023  16:59           196,800 carpet-extra-1.19.3-1.4.91.jar
08/01/2023  18:27         1,143,110 cloth-config-9.0.94-fabric.jar
08/01/2023  18:22           974,522 CreativeCore_FABRIC_v2.9.3_mc1.19.3.jar
08/01/2023  18:23            29,513 DamageTilt-1.19-fabric-0.1.2.jar
11/01/2023  16:49         1,535,456 fabric-carpet-1.19.3-1.4.93+v221230.jar
08/01/2023  18:25           152,102 fallingleaves-1.14.3+1.19.3.jar
10/01/2023  17:20         1,037,704 freecam-fabric-1.1.8+1.19.jar
08/01/2023  18:25           118,628 indium-1.0.12+mc1.19.3.jar
08/01/2023  18:24         2,265,058 iris-mc1.19.3-1.5.1.jar
08/01/2023  18:27           559,472 lambdynamiclights-2.2.0+1.19.3.jar
11/01/2023  18:12                14 List.bat
11/01/2023  18:12                 0 list.txt
10/01/2023  17:17           120,017 logical_zoom-0.0.18.jar
11/01/2023  16:40           514,974 malilib-fabric-1.19.3-0.14.0.jar
08/01/2023  18:46           637,090 modmenu-5.0.2.jar
08/01/2023  18:40           537,475 NoChatReports-FABRIC-1.19.3-v1.19.0.jar
08/01/2023  18:22         7,237,111 PresenceFootsteps-1.7.1.jar
08/01/2023  18:12         1,657,429 qfapi-4.0.0-beta.25_qsl-3.0.0-beta.24_fapi-0.70.0_mc-1.19.3.jar
08/01/2023  18:21            36,633 raised-fabric-1.19.3-1.1.4.jar
08/01/2023  18:24            49,984 reeses_sodium_options-1.4.9+mc1.19.2-build.67.jar
08/01/2023  18:29         1,204,420 shulkerboxtooltip-fabric-3.2.4+1.19.3.jar
08/01/2023  18:24           264,066 sodium-extra-0.4.16+mc1.19.3-build.91.jar
08/01/2023  18:24           715,490 sodium-fabric-mc1.19.3-0.4.8+build.22.jar
08/01/2023  19:21           105,849 soundphysics-fabric-1.19.3-1.0.18.jar
08/01/2023  18:28           127,465 starlight-1.1.1+fabric.ae22326.jar
11/01/2023  16:34           272,551 tweakeroo-fabric-1.19.3-0.15.0.jar
09/01/2023  18:04         5,356,489 viafabric-0.4.9+23-main.jar

**Comment by ghost** [comment]
UPDATE: The default f3 screen is also not showing much information. I think a mod is changing something

**Comment by ghost** [comment]
I vaguely remember pressing an option that says: reduce f3 info or something like that somewhere

**Comment by TreyRuffy** [comment]
It's in the Minecraft settings, not the betterf3 settings. It exists in the multiplayer settings. Alternatively, it could be the gamerule reducedDebugInfo is set to true.

**Comment by ghost** [comment]
the gamerule is set to false. There is also no option to do with f3 in the multiplayer settings

**Comment by TreyRuffy** [comment]
Once you open the client, click options, chat settings, and turn off reduced debug info.
