### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Mythixfps** [cominixo/BetterF3#141]
### Describe the Bug

when i try to add or edit a module it says "saving world" as in i jus left a world and then the game just crashes, same with if i hit general settings, only thing i can do is delete and move the pre existing modules

### Steps to Reproduce

tbh ion know what this means. i think ur asking how to make it happen? if so jus hit any of the 3 buttons i said describing the bug

### Expected Behavior

i expected it to either take me to general settings, add a new module or edit a preexisting module, not crash

### Modloader Type

Fabric

### Modloader Version

newest so it would be the one for 1.19,4

### Mod Version

BetterF3-6.0.0-Fabric-1.19.4-pre3.jar

**Comment by TreyRuffy** [comment]
You need to update the cloth config version.
