### ISSUE TITLE
1.19.4 for Forge?

### ISSUE THREAD

**Issue by Aetrnl94** [cominixo/BetterF3#143]
### Describe the Request

Hi! This mod looks really great. I was wondering if you might be able to let us know if you're working on the 1.19.4 Forge version, and if so, when it might be out? Thank you much and I can't wait to try it out!

### Modloader Type

Minecraft Forge

### Modloader Version

Latest

**Comment by TreyRuffy** [comment]
Fixed in 6.0.1

**Comment by Aetrnl94** [comment]
Awesome, thank you so much!
