### ISSUE TITLE
[Bug]: forceloaded chunks value on display is different from number of elements in "/forceload query" result

### ISSUE THREAD

**Issue by hendrikvalentim** [cominixo/BetterF3#146]
### Describe the Bug

Looking at the on-screen output next to "Forceloaded chunks", the value displayed is zero, while the set of chunks I get when issuing `/forceload query` has a count of 28.

### Steps to Reproduce

Unknown how it went from working as expected to not working. It never showed the value that I expect.

### Expected Behavior

Value shown on in-game UI for "forceloaded chunks" matches the count of chunks which the server reports.

### Screenshots

![2023-05-20_16 28 11](https://github.com/cominixo/BetterF3/assets/8114478/7702bbcd-4e95-48d7-bf0e-a66cc89084af)

### Modloader Type

Fabric

### Modloader Version

0.14.19

### Mod Version

6.0.1

### Log Output

```shell
[16:22:38] [Render thread/INFO]: [System] [CHAT] 28 force loaded chunks were found in minecraft:overworld at: [-17, -68], [-16, -68], [-16, -67], [-14, -13], [-11, -12], [-10, -12], [-17, -11], [-16, -11], [-15, -11], [-14, -11], [-13, -11], [-12, -11], [-11, -11], [-10, -11], [-17, -10], [-16, -10], [-15, -10], [-14, -10], [-13, -10], [-12, -10], [-11, -10], [-10, -10], [-5, -10], [-4, -10], [-17, -9], [-16, -9], [-17, -8], [-296, 601]
```

### Additional Context
Player is located near spawn.

## Server
Paper version git-Paper-538 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bcd8dc2)
server plugin BetterSleeping4 v4.0.1
server plugin ConcreteMixer v1.2.0
server plugin spark v1.10.38

## Client
[11:22:14] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.19
[11:22:14] [main/INFO]: Loading 58 mods:
	- betterf3 6.0.1
	   \-- cloth-config 10.0.96
	        \-- cloth-basic-math 0.6.1
	- fabric-api 0.80.0+1.19.4
	   |-- fabric-api-base 0.4.25+504944c8f4
	   |-- fabric-api-lookup-api-v1 1.6.26+504944c8f4
	   |-- fabric-biome-api-v1 13.0.8+348a9c64f4
	   |-- fabric-block-api-v1 1.0.7+e022e5d1f4
	   |-- fabric-blockrenderlayer-v1 1.1.35+c2e6f674f4
	   |-- fabric-client-tags-api-v1 1.0.16+504944c8f4
	   |-- fabric-command-api-v1 1.2.28+f71b366ff4
	   |-- fabric-command-api-v2 2.2.7+504944c8f4
	   |-- fabric-commands-v0 0.2.45+df3654b3f4
	   |-- fabric-containers-v0 0.1.55+df3654b3f4
	   |-- fabric-content-registries-v0 3.5.10+ae0966baf4
	   |-- fabric-convention-tags-v1 1.4.2+9a7c5daaf4
	   |-- fabric-crash-report-info-v1 0.2.16+aeb40ebef4
	   |-- fabric-data-generation-api-v1 11.4.1+504944c8f4
	   |-- fabric-dimensions-v1 2.1.46+7f87f8faf4
	   |-- fabric-entity-events-v1 1.5.14+504944c8f4
	   |-- fabric-events-interaction-v0 0.5.0+76ba65ebf4
	   |-- fabric-events-lifecycle-v0 0.2.53+df3654b3f4
	   |-- fabric-game-rule-api-v1 1.0.34+a1ccd7bff4
	   |-- fabric-item-api-v1 2.1.18+504944c8f4
	   |-- fabric-item-group-api-v1 3.0.6+043f9acff4
	   |-- fabric-key-binding-api-v1 1.0.34+504944c8f4
	   |-- fabric-keybindings-v0 0.2.32+df3654b3f4
	   |-- fabric-lifecycle-events-v1 2.2.16+504944c8f4
	   |-- fabric-loot-api-v2 1.1.28+75e98211f4
	   |-- fabric-loot-tables-v1 1.1.32+9e7660c6f4
	   |-- fabric-message-api-v1 5.1.2+504944c8f4
	   |-- fabric-mining-level-api-v1 2.1.40+49abcf7ef4
	   |-- fabric-models-v0 0.3.31+504944c8f4
	   |-- fabric-networking-api-v1 1.3.2+504944c8f4
	   |-- fabric-networking-v0 0.3.42+df3654b3f4
	   |-- fabric-object-builder-api-v1 7.0.4+504944c8f4
	   |-- fabric-particles-v1 1.0.24+f1e4495bf4
	   |-- fabric-recipe-api-v1 1.0.9+a1ccd7bff4
	   |-- fabric-registry-sync-v0 2.2.1+504944c8f4
	   |-- fabric-renderer-api-v1 2.2.6+504944c8f4
	   |-- fabric-renderer-indigo 1.1.2+81e8c576f4
	   |-- fabric-renderer-registries-v1 3.2.39+df3654b3f4
	   |-- fabric-rendering-data-attachment-v1 0.3.29+afca2f3ef4
	   |-- fabric-rendering-fluids-v1 3.0.22+504944c8f4
	   |-- fabric-rendering-v0 1.1.42+df3654b3f4
	   |-- fabric-rendering-v1 2.1.2+504944c8f4
	   |-- fabric-resource-conditions-api-v1 2.3.2+e6c7d4eef4
	   |-- fabric-resource-loader-v0 0.11.3+1e1fb126f4
	   |-- fabric-screen-api-v1 1.0.46+504944c8f4
	   |-- fabric-screen-handler-api-v1 1.3.21+504944c8f4
	   |-- fabric-sound-api-v1 1.0.10+504944c8f4
	   |-- fabric-transfer-api-v1 3.1.2+504944c8f4
	   \-- fabric-transitive-access-wideners-v1 3.0.4+504944c8f4
	- fabricloader 0.14.19
	- java 17
	- minecraft 1.19.4
	- modmenu 6.2.2
	- sodium 0.4.10+build.24

**Comment by hendrikvalentim** [comment]
I have only just started using plugins and mods. Please be kind. 🙏🏼

**Comment by TreyRuffy** [comment]
Unfortunately, because it is on a server, the mod does not have a way to read this value. The value will also be absent from the vanilla F3 menu because of this. I do not have plans to add this feature yet, but maybe in the future
