### ISSUE TITLE
[Bug]: Missing some "format.betterf3.X" strings for translation

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [cominixo/BetterF3#148]
### Describe the Bug

Hello! I noticed that not all "format.betterf3.X" strings are available for translation...

I compared all strings of that type in Github project's en_us.json file of this mod and all strings of that type in Crowdin search... (https://imgur.com/a/ipQeE2V) And I found out that these strings are currently missing: "format.betterf3.no_format", "format.betterf3.total" (can be useful, for example, for Tatar language... because en_us.json forces unnatural order of string links for this language (and probably for Russian language too)), "format.betterf3.default_no_colon", "format.betterf3.default_format".

### Steps to Reproduce

Check the Crowdin Project and en_us.json to compare them.

### Expected Behavior

The strings should be available in Crowdin for translation.

### Modloader Type

Fabric

### Modloader Version

Any

### Mod Version

Any

### Additional Context

I suggest to fix that small issue by adding opportunity to translate those strings for all languages.

And [this bug](https://crowdin.com/project/betterf3/discussions/3) was reported by Me 3 months ago in Crowdin Project, but I still can't get any feedback.

**Comment by TreyRuffy** [comment]
I have made them visible now.
