### ISSUE TITLE
Crashing with Canvas Render

### ISSUE THREAD

**Issue by UltraBlackLinux** [cominixo/BetterF3#16]
Hey, there,
I am currently experiencing a crash, when opening the debug hud, while using Canvas Renderer.
Crash log: https://paste.ee/p/Q4inJ (Ignore the GL errors, that's also a Canvas problem I currently have lol)

Thanks!

**Comment by cominixo** [comment]
Huh, I'm pretty sure it worked fine with Canvas when I tested it, can you reproduce this on 1.1.2 and only with BetterF3 and Canvas?

**Comment by UltraBlackLinux** [comment]
> Huh, I'm pretty sure it worked fine with Canvas when I tested it, can you reproduce this on 1.1.2 and only with BetterF3 and Canvas?

Yep. Still crashing.

**Comment by cominixo** [comment]
Fixed in 1.1.4, let me know if it's still crashing
