### ISSUE TITLE
[Bug]: In versions for 1.19.3 an empty list of modules for the left and right sides

### ISSUE THREAD

**Issue by SergoZar** [cominixo/BetterF3#160]
### Describe the Bug

When you go to the menu for adding modules for the left or right side, there are no modules in the list

### Steps to Reproduce

1. Press F3+M
2. Click "Left Modules" and "Right Modules"
3. Click "Add Module"

### Expected Behavior

In the module list there are modules that you can choose to add for the left or right side

### Screenshots

![CopyQ yNWFGX](https://github.com/cominixo/BetterF3/assets/67230600/c99226ba-c571-474a-9198-d630efbaf763)
![CopyQ PeUNlk](https://github.com/cominixo/BetterF3/assets/67230600/a58b9fff-0efa-4012-b691-705f2830df63)
![CopyQ WeVfxG](https://github.com/cominixo/BetterF3/assets/67230600/b78b7833-6b49-4c43-9471-e5d6f2bf0beb)

![CopyQ ieknOC](https://github.com/cominixo/BetterF3/assets/67230600/790137d9-80be-4a0e-a0f5-6bed4d8012a5)
![CopyQ KGOwxv](https://github.com/cominixo/BetterF3/assets/67230600/c3686e09-139e-40a6-ab7e-275368db145c)
![CopyQ umQJYH](https://github.com/cominixo/BetterF3/assets/67230600/bec709d9-bc9f-4e9e-b041-fab1611dfea5)

### Modloader Type

Minecraft Forge

### Modloader Version

fabric-api-0.76.1+1.19.3

### Mod Version

5.0.0

**Comment by TreyRuffy** [comment]
You are able to backspace "Seperator" and replace it with another module.
