### ISSUE TITLE
Game Crashes when opening Debug Screen

### ISSUE THREAD

**Issue by MopsTMC** [cominixo/BetterF3#17]
Hello, I've been using this mod for quite a while and today I wanted to test it with some other mods. It seems that only sometimes it crashes the game when pressing F3 as it managed to work once. I'm sorry I can't provide much other than the crash log but hope it helps in finding what causes this.
[crash-2021-02-21_14.31.17-client.txt](https://github.com/cominixo/BetterF3/files/6017699/crash-2021-02-21_14.31.17-client.txt)

**Comment by cominixo** [comment]
Thanks for reporting, I'll look into it!

**Comment by MopsTMC** [comment]
It seems to me that the crash happens when the mod tries to load the biome name of custom/modified biomes, although I'm not fully sure. The crash happens less frequently on servers.

**Comment by MopsTMC** [comment]
RandomPatches might have been the culprit eventually as I mentioned above.

**Comment by jklw10** [comment]
https://gist.githubusercontent.com/natanfudge/d75065dd1e45e332ad0afa31668dcbc6/raw/f71ac1c2c5594e9f25eeaa3f39eb81fd9a96e062/crash.txt
i got a similar issue. it says BF3 is the issue.

**Comment by MopsTMC** [comment]
Yes, my crash logs are really similar to this. What is weird though is that there isn't an obvious pattern or particular cause of when it crashes. I tried running the mod in a debug environment to test try and figure something out but the project wouldn't build unfortunately.

**Comment by cominixo** [comment]
Seems to be related with the same crash that happens when using Canvas

**Comment by cominixo** [comment]
Should be fixed with 1.1.4, let me know if it still crashes!
