### ISSUE TITLE
[Suggestion] Add option to change font size

### ISSUE THREAD

**Issue by SpacEagle17** [cominixo/BetterF3#18]
The only way for me to see the entire f3 menu is to change the GUI Scale to 2, but that also reduces all the other GUI's and it can become to small. The best way to solve this problem is by having a setting to change the font size. A good example for this is minihud, where the font scale is independent of Minecraft's GUI scale and the user is able to change it.
![2021-03-31_12 04 33](https://user-images.githubusercontent.com/46494907/113127653-4be3f380-9219-11eb-81fa-c5929b1ced1a.png)

**Comment by cominixo** [comment]
Closed with #26
