### ISSUE TITLE
[Suggestion] BetterF3 for 1.15.2

### ISSUE THREAD

**Issue by GhastRs** [cominixo/BetterF3#19]
We need it, too. It's a good mod. Please make a mod for **Minecraft 1.15.2**, thank you very much!
:D

**Comment by cominixo** [comment]
This would be very hard to do on 1.15, it doesn't have RGB text like 1.16 does, so it would be limited to the 16 colors that are available there. Even then, it's still quite a bit of work for a version that's more than a year old. If anyone else wants to port it they can of course, I just don't have any plans to.
