### ISSUE TITLE
Cannot have 2 different "System" on the right side

### ISSUE THREAD

**Issue by iPollox** [cominixo/BetterF3#2]
I'm trying to have a separation between java version and memory allocations and the specs of my pc, but when adding a second "System" they both get edited

![2020-08-13_02 59 35](https://user-images.githubusercontent.com/5094754/90103826-28634b80-dd11-11ea-8b5a-1d684e71f5ce.png)

**Comment by cominixo** [comment]
Should be simple to fix, I'll take a look at it later. Thanks for the report!

**Comment by cominixo** [comment]
This has been fixed, will be in v1.1
