### ISSUE TITLE
[Suggestion] Configure the mod to be client only

### ISSUE THREAD

**Issue by starmun-0010** [cominixo/BetterF3#21]
Please configure the mod to be client only so that servers do not show up as incompatible in the multiplayer menu.

**Comment by cominixo** [comment]
This is already the case, even if it wasn't it wouldn't interfere with joining multiplayer servers, as this mod doesn't use anything server-side. It's likely that the server you're trying to join blocks all players that have Fabric installed.

**Comment by starmun-0010** [comment]
![image](https://user-images.githubusercontent.com/5557278/114917389-53bdad80-9e3f-11eb-98f9-0ea3691814da.png)

It is my custom 1.16.5 forge modpack. There is no fabric involved. It does not prevent from joining but the big red X mark is not good for modpack users.

![image](https://user-images.githubusercontent.com/5557278/114917677-a8612880-9e3f-11eb-8ffa-431db82327a8.png)

**Comment by cominixo** [comment]
Oh, my bad. This should be in https://github.com/TreyRuffy/BetterF3 as I don't maintain the Forge version.

**Comment by starmun-0010** [comment]
Oh, I apologize, I followed the issue link from CurseForge and did not realize that this is the fabric repo.
Thanks for letting me know.
