### ISSUE TITLE
Mod Compatibility issue

### ISSUE THREAD

**Issue by zachsai** [cominixo/BetterF3#22]
Make your mod work on server so you can get:
![image](https://user-images.githubusercontent.com/63996164/115977133-1cd44f80-a543-11eb-93e5-26dae96648a3.png)

instead of the X for incompatible mods.
1.16.5

**Comment by cominixo** [comment]
Duplicate of #21, already fixed in the Forge fork (https://github.com/TreyRuffy/BetterF3/issues/3).
