### ISSUE TITLE
New font-scale option misplaces the TPS/FPS graph (alt-f3)

### ISSUE THREAD

**Issue by MeeniMc** [cominixo/BetterF3#27]
The new font-scale option does not place properly the TPS/FPS graph axis and labels that is obtained by hitting alt-f3 keybinds.

The graph itself is rendered at the correct position, but the axis and boxes are moved to a 'scaled down' position.

Replication steps: 

1. set font-scale to 0.5
2. hit alt-f3
3. see the TPS box appear in the center of the screen while the TPS graph itself (green-bars) appears at its normal position and is not scaled (I think the latter is intentional).

**Comment by thedocruby** [comment]
I second this, it bothers me a lot since i regularly use the TPS box to monitor the health of my server. Hopefully it can be fixed in 1.18?
![2021-12-04_12 36 48](https://user-images.githubusercontent.com/76263371/144719076-41db7889-98cd-49cf-a073-3ff2f8aa86fd.png)

**Comment by thedocruby** [comment]
@TreyRuffy TYSM! This helps a lot!

**Comment by MeeniMc** [comment]
This works great in single player. 

The TPS box is still misplaced when used on a server, in combination with ServerTick https://github.com/sammko/servertick-fabric (otherwise the TPS box would not be visible)

**Comment by TreyRuffy** [comment]
> This works great in single player.
> 
> The TPS box is still misplaced when used on a server, in combination with ServerTick [sammko/servertick-fabric](https://github.com/sammko/servertick-fabric) (otherwise the TPS box would not be visible)

Just fixed that in dde1673! The fact there were two mixins for the same method was just screwing up the scaling.
