### ISSUE TITLE
The mod crashes when the name of a configuration is clicked

### ISSUE THREAD

**Issue by RaiderxD404** [cominixo/BetterF3#29]
With modmenu, in configuration / left modules when you click on the name of an option it crashes

Mods I am using:

BetterF3

Inmis

Mod Menu

OmegaCraft (config mod for BetterF3 (?)

Version used: Fabric 1.17 (No snapshot) (Latest Version)

Mod version: BetterF3-1.1.3 + 1.17-pre1
[crash-2021-06-09_19.44.33-client.txt](https://github.com/cominixo/BetterF3/files/6627488/crash-2021-06-09_19.44.33-client.txt)

**Comment by cominixo** [comment]
Thanks for the report, I'll look into it as soon as I can

**Comment by cominixo** [comment]
Fixed with the latest commit, I'll make a release soon
