### ISSUE TITLE
Crashing with Canvas Render

### ISSUE THREAD

**Issue by Wilson1020** [cominixo/BetterF3#30]
I tried without Canvas Render, it could work.
When i turned it to the origin f3 with Canvas Render, it could work.
When i turned it on with Canvas Render, it crashed.
version:1.17
[crash-2021-06-10_11.42.53-client.txt](https://github.com/cominixo/BetterF3/files/6628184/crash-2021-06-10_11.42.53-client.txt)

**Comment by cominixo** [comment]
Duplicate of #16 , I'll try to look into it today
