### ISSUE TITLE
crash when i want to change the setting with modmenu

### ISSUE THREAD

**Issue by gamingoninsulin** [cominixo/BetterF3#32]
when i want to change something in the better f3 mod screen with ModMenu it chrashes

crash log:

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 11-06-2021 17:37
Description: Narrating screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2561.getString()" because "â˜ƒ" is null
	at net.minecraft.class_6382.method_37034(class_6382.java:8)
	at net.minecraft.class_4280$class_4281.method_37020(class_4280.java:63)
	at net.minecraft.class_4280.method_37020(class_4280.java:40)
	at net.minecraft.class_437.method_37056(class_437.java:593)
	at net.minecraft.class_437.method_37062(class_437.java:576)
	at net.minecraft.class_6385.method_37044(class_6385.java:34)
	at net.minecraft.class_437.method_37065(class_437.java:566)
	at net.minecraft.class_437.method_37071(class_437.java:553)
	at net.minecraft.class_757.method_3192(class_757.java:890)
	at net.minecraft.class_310.method_1523(class_310.java:1114)
	at net.minecraft.class_310.method_1514(class_310.java:730)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_6382.method_37034(class_6382.java:8)
	at net.minecraft.class_4280$class_4281.method_37020(class_4280.java:63)
	at net.minecraft.class_4280.method_37020(class_4280.java:40)
	at net.minecraft.class_437.method_37056(class_437.java:593)
	at net.minecraft.class_437.method_37062(class_437.java:576)
	at net.minecraft.class_6385.method_37044(class_6385.java:34)
	at net.minecraft.class_437.method_37065(class_437.java:566)
	at net.minecraft.class_437.method_37071(class_437.java:553)

-- Screen details --
Details:
	Screen name: me.cominixo.betterf3.config.gui.modules.ModulesScreen

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: Default, Fabric Mods, cullleaves/smartleaves, lambdabettergrass/default
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:749)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 863952128 bytes (823 MiB) / 3888119808 bytes (3708 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 3,40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 4000
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 2112,00
	Graphics card #0 deviceId: 0x0162
	Graphics card #0 versionInfo: DriverVersion=10.18.10.5161
	Graphics card #1 name: NVIDIA GeForce GTX 780
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 3072,00
	Graphics card #1 deviceId: 0x1004
	Graphics card #1 versionInfo: DriverVersion=27.21.14.5709
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 1,60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 1,60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 18698,48
	Virtual memory used (MB): 10766,10
	Swap memory total (MB): 2432,00
	Swap memory used (MB): 0,00
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		architectury: Architectury 2.0.8
		artisanat: Artisanat 2.1
		betterf3: BetterF3 1.1.4
		biome_locator: Biome Locator 1.1.2
		bitsandchisels: BitsAndChisels 2.5.0
		cardinal-components-base: Cardinal Components API (base) 3.0.0-nightly.1.17-pre1
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0-nightly.1.17-pre1
		carrier: Carrier 1.8.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		conjuring: Conjuring 1.0.3
		controlling: Controlling For Fabric 1.1.2
		crusade: Crusade 1.2.4
		cullleaves: Cull Leaves 2.2.0
		dawn: Dawn API 2.0.2
		de_javagl_obj: obj 0.3.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dynamicfps: Dynamic FPS 2.0.3
		editsign: EditSign 2.2.1
		extratnt: Extra TNT 1.0.2
		fabric: Fabric API 0.34.10+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.2+a02b44633d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+9e521e133d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.8+a02b44633d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b44633d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.1+kotlin.1.5.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab61213d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.9+a02b44633d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121a0
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.3+b7ab61213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.10+be9da3103d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabricloader: Fabric Loader 0.11.3
		fallingleaves: Falling Leaves 1.7.0+1.17
		fallingtree: FallingTree 2.11.3
		fatxporbs: Fat Experience Orbs 1.0.0
		fishonaleash: Fish on a Leash! 1.17-1.0.0
		flytre_lib: FlytreLib 0.2.13
		golemsgalore: Golems Galore 1.0.2+mc.1.17
		grass_pass: Grass Bypass 1.0.0
		improved-stations: Improved Stations 2.0.5
		inventoryhud: Inventory HUD + 3.3.1
		itemscroller: Item Scroller 0.15.0-dev.20210608.211652
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 16
		lambdabettergrass: LambdaBetterGrass 1.2.0+1.17
		lambdynlights: LambDynamicLights 2.0.0+1.17
		libblockattributes: LibBlockAttributes 0.8.17003
		libblockattributes_core: LibBlockAttributes (Core) 0.8.17003
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.17003
		libblockattributes_items: LibBlockAttributes (Items) 0.8.17003
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.0.0-beta.3+1.17-pre1
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.0
		malilib: MaLiLib 0.10.0+dev.22
		minecraft: Minecraft 1.17
		minecraftcapes: MinecraftCapes Mod 10
		mo_glass: Mo Glass 1.5-MC1.17
		mocolors: Mo' Colors 1.2.0
		modmenu: Mod Menu 2.0.0-beta.7
		morevillagers-fabric: MoreVillagersFabric 2.0.0-SNAPSHOT
		mostructures: Mo' Structures 1.2.0-pre1+mc.1.17
		myron: Myron 1.6.0
		neutral_animals: Neutral Animals 1.0.1
		omega-config: OmegaConfig ${version}
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		org_objenesis_objenesis: objenesis 3.2
		owo: OwO 0.1
		plantinajar: Plant In A Jar 2.2.1
		promenade: Promenade 2.1.2
		respawnablepets: Respawnable Pets 1.17-1
		roughlyenoughitems: Roughly Enough Items 6.0.249-alpha
		rsmm-fabric: Redstone Multimeter Fabric 1.3.0
		spruceui: SpruceUI 3.1.0+1.17
		stacc: Stacc 1.0.1
		structurized: Structurized 1.3.0
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		universal_ores: Universal Ores 1.0
		veinmining: Vein Mining 0.0.8-1.17
		verticalrepeaters: Vertical Repeaters 1.1.0
		voxelmap: VoxelMap 1.10.15
		xlpackets: XLPackets 1.1
	Launched Version: 1.17
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 780/PCIe/SSE2 GL version 3.2.0 NVIDIA 457.09, NVIDIA Corporation
	Window size: 1440x900
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, cullleaves/smartleaves, lambdabettergrass/default
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz

to re produse:
  use fabric 1.17 11.0.3 
  use modmenu 2.0.0 beta 7 
  I downloaded all files trough GDLauncher 

navigate to:
  mods ->  betterf3 -> click right or left and then any button it crashes

**Comment by cominixo** [comment]
This was fixed in 1.1.5, update and it should work as normal.

**Comment by gamingoninsulin** [comment]
oh thank you didnt knew
