### ISSUE TITLE
1.17 game crashing when editing rigth modules

### ISSUE THREAD

**Issue by Brylkss** [cominixo/BetterF3#33]
So when I try to edit Rigth Models my game just crashes, and when I join the game again it resets my f3 configs
[crash-2021-06-21_14.44.06-client.txt](https://github.com/cominixo/BetterF3/files/6688604/crash-2021-06-21_14.44.06-client.txt)

also im using Fabric api, optifabric, optifine, perspective mod and better f3 as mods

**Comment by cominixo** [comment]
Hey, please update to BetterF3 1.1.5
