### ISSUE TITLE
Crash when deleting an item with no selection

### ISSUE THREAD

**Issue by limelier** [cominixo/BetterF3#34]
Steps to reproduce:
1. Go to the BetterF3 mod settings.
2. Go to Left Modules.
3. Select the first module.
4. Delete it. There will be no selection, but the delete button is still clickable.
5. Click the delete button again.

I think the expected behavior would be to either disable the delete button, or select the next item in the list.

Crash log, using "Not Enough Crashes": https://gist.githubusercontent.com/natanfudge/e2921fbe4bd4cdd2085e838388bfd2de/raw/5fe8b1f55b79a83dd4a10c65f195ef0b4e17a1da/crash.txt

**Comment by cominixo** [comment]
Thanks for the report! I'll look into it
