### ISSUE TITLE
The mod is broken

### ISSUE THREAD

**Issue by turtlehaku** [cominixo/BetterF3#37]
When I use betterf3 with better mc with the server pack it doesn't work and it didnt work ever since I did /time add 9999d but it worked before and my friend says sometimes mods break so I know how to fix it

**Comment by cominixo** [comment]
Could you provide a crash log or more specific steps to reproduce this?

**Comment by TreyRuffy** [comment]
Closing unless there is a crash report to suggest the issue still exists.
