### ISSUE TITLE
The menu gets cut off with GUI scale of 3 or higher

### ISSUE THREAD

**Issue by JumperREDACTED** [cominixo/BetterF3#39]
GUI scale 2
![image](https://user-images.githubusercontent.com/83337894/127300738-01cc5f76-838f-42c9-ae00-1c1ae7bb9d7c.png)

GUI scale 3
![image](https://user-images.githubusercontent.com/83337894/127300781-1596feb9-ad17-42e6-884d-e4fe31ada067.png)

Logs:
[latest.log](https://github.com/cominixo/BetterF3/files/6891986/latest.log)

**Comment by cominixo** [comment]
Nothing much to do here, you can scale the font in the configuration so it doesn't get cut off, or remove some lines/modules you don't need
