### ISSUE TITLE
Game crashes after pressing Done button

### ISSUE THREAD

**Issue by Rafii2198** [cominixo/BetterF3#4]
### [Minecraft 1.16.3 | Fabric 0.10.0+build.209 using MultiMC]
I made a small modpack with client-side mods and whenever I try to change anything in Better F3 from in-game config, the game crashes.
To be exact: The game crashes whenever I click the **Done** button in either Left or Right module section. Changes are saved though.
Crash report: [crash-2020-10-06_15.25.43-client.txt](https://github.com/cominixo/BetterF3/files/5334124/crash-2020-10-06_15.25.43-client.txt)

**Comment by cominixo** [comment]
Looks like you're using an older version of BetterF3. Update to the latest one, if I recall correctly this was already fixed.

**Comment by Rafii2198** [comment]
I downloaded it today from Curseforge

**Comment by cominixo** [comment]
Are you sure? The crash log says you're on version 1.0, latest is 1.1.1. Also, you're using Minecraft 1.16.1, not 1.16.3.

**Comment by Rafii2198** [comment]
Yea. MultiMC and main menu shows me that I have loaded 1.16.3, I also just downloaded newest version from github. And I just looked at the log I sent and on line 54 it says it is Minecraft 1.16.3 and on line 68 it says that I have BetterF3 1.1.1

**Comment by Rafii2198** [comment]
Here is newer log if you need with the one from github [crash-2020-10-06_15.51.19-client.txt](https://github.com/cominixo/BetterF3/files/5334326/crash-2020-10-06_15.51.19-client.txt)

**Comment by cominixo** [comment]
Yeah that looks like the right one, I'll take a look at it.

**Comment by cominixo** [comment]
For now, you could try to delete your config file (or just move it somewhere else) in `.minecraft/config/betterf3.json`, that should fix it.

**Comment by Rafii2198** [comment]
Wait I just noticed something, there is nothing named betterf3 in the config folder, so I tested why it was saving changes as there is no file, so I noticed it saved only because I used Not Enough Crashes so I can go back to the main menu after the crash but when I relaunched Minecraft they were brought back to default.

I assume the mod has some difficulties writing config file on Linux, I think should mention it in the main post, my apologies.

**Comment by cominixo** [comment]
I don't think Linux is the issue, always tested the mod on Linux and it works. I'm suspecting it might be something related to LambdaControls using a different version of NightConfig.

**Comment by Rafii2198** [comment]
Just disabled LambdaControls and now it works perfectly! Should I open an issue on their github?

**Comment by cominixo** [comment]
Thanks for testing. I think it might be more my fault than theirs though. I'll try updating my nightconfig later.

**Comment by Rafii2198** [comment]
Glad I could help :smiley:

**Comment by cominixo** [comment]
Actually, seems like LambdaControls has an older version of NightConfig, not sure how to fix it unless I downgrade mine, or LambdaControls updates theirs.

**Comment by LambdAurora** [comment]
This issue has been fixed in LambdaControls 1.6.0. So I think it can be closed.

**Comment by cominixo** [comment]
Thanks!
