### ISSUE TITLE
Debug Pie Chart Does Not Respect GUI Scale

### ISSUE THREAD

**Issue by ghost** [cominixo/BetterF3#52]
See the bottom right:
![image](https://user-images.githubusercontent.com/24266948/144696908-66591b6b-9ae3-47c6-892e-44c069c662db.png)

**Comment by TreyRuffy** [comment]
What version of the mod are you using? I believe I fixed it in v1.2.0.

Edit: Have you modified the font size in the BetterF3 menu?

https://www.curseforge.com/minecraft/mc-mods/betterf3/files/3548032

**Comment by ghost** [comment]
I have not modified the font size (completely default settings), and I am using v1.2.0.

**Comment by TreyRuffy** [comment]
Ok, I believe I have fixed it in my latest commit! 5e9d4be
