### ISSUE TITLE
[Bug]: Unlocalized "text.betterf3.line.axolotls"

### ISSUE THREAD

**Issue by AeiouEnigma** [cominixo/BetterF3#58]
### Describe the Bug

The Entities module displays an unlocalized name for the Axolotls line.

### Steps to Reproduce

Yes

### Expected Behavior

This line should instead display "Axolotls"

### Screenshots

![image](https://user-images.githubusercontent.com/3160746/146877487-c9af4063-8fc7-4b5a-b1bf-09e3f83125a3.png)

### Modloader Type

Fabric

### Modloader Version

0.12.12

### Mod Version

1.2.2

**Comment by TreyRuffy** [comment]
We have the commit already pushed but it just hasn't constituted a new release. I would recommend just downloading the latest version from [here](https://github.com/cominixo/BetterF3/actions/runs/1543705636). Just click on test-results and head into the respective folder to find the latest version jar.
