### ISSUE TITLE
[Bug]: Incompatibility with wthit (1.18 port waila)

### ISSUE THREAD

**Issue by fungoza** [cominixo/BetterF3#59]
### Describe the Bug

With this mod, information from the wthit mod is not shown at the top of the screen.

### Steps to Reproduce

Install wthit

### Expected Behavior

?

### Screenshots

![2021-12-29_16 03 05](https://user-images.githubusercontent.com/68079109/147660371-531bfbde-76f7-43cf-8052-5b9becf7937c.png)
![2021-12-29_16 03 11](https://user-images.githubusercontent.com/68079109/147660376-a381638f-8ee9-4ef2-ac4a-47b396422628.png)

### Modloader Type

Fabric

### Modloader Version

fabric-loader-0.12.11-1.18.1

### Mod Version

1.2.2

**Comment by MeeniMc** [comment]
This is not a bug: open the wthit config (default key: 0), click "WTHIT Settings", unclick "Hide from Debug" to False (True by default), and it will work the way you want.
