### ISSUE TITLE
Light Level not showing 

### ISSUE THREAD

**Issue by Donkeysbanana** [cominixo/BetterF3#60]
Currently playing Valhelsia enhanced vanilla with betterf3 enabled, the light level doesn't display any information. When betterf3 is disabled, the vanilla minecraft displays the light level.
![betterf3 light level screen shot ](https://user-images.githubusercontent.com/81700718/147873338-891cca26-d889-4379-b441-609454878a95.png)
![Screenshot Vanilla light level](https://user-images.githubusercontent.com/81700718/147873340-9cf49bc1-2182-4acd-8b38-94d5e04aff18.png)
l

**Comment by nojusmurauskas** [comment]
I had the same problem and I found that immersive portals mod caused this behavior for me at least.

**Comment by TreyRuffy** [comment]
Closed in 4.0.0
