### ISSUE TITLE
[Bug]: gui size

### ISSUE THREAD

**Issue by AbyssalBytez** [cominixo/BetterF3#61]
### Describe the Bug

I have gui set to 2 in other videos I see they set to 2 and see all but mine gets cut off when I change to 1 see all but I want minimum 2gui scale to see properly

### Steps to Reproduce

Idk

### Expected Behavior

Adjust in all gui types

### Modloader Type

Fabric

### Modloader Version

1.18.1-1.12.12

### Mod Version

V1.2.2

**Comment by TreyRuffy** [comment]
Change the font scale in the mod to a value lower than one (such as .6) to make it 60% of it's original size.
