### ISSUE TITLE
[Bug]: Mod not usable through Curseforge client

### ISSUE THREAD

**Issue by Akorian** [cominixo/BetterF3#62]
### Describe the Bug

When creating a Fabric Modpack with ver 1.18.1 it is impossible to add betterf3 even though it is usable in 1.18.1. 

### Steps to Reproduce

Try to create a fabric modpack with the latedt MC and fabric version then try to add the mod.

### Expected Behavior

When creating a Modpack with the latest version, I would expect BetterF3 to be available to install.

### Modloader Type

Fabric

### Modloader Version

0.12.12

### Mod Version

v1.2.2

**Comment by TreyRuffy** [comment]
I believe I fixed it. Try again now!
