### ISSUE TITLE
[Feature] Softly unload the mod if loaded on a server environment

### ISSUE THREAD

**Issue by Sunekaer** [cominixo/BetterF3#63]
### Describe the Bug

Mod crashes servers

### Steps to Reproduce

load mod on server

### Expected Behavior

To not crash 

### Modloader Type

Minecraft Forge

### Modloader Version

39.0.10

### Mod Version

BetterF3-1.2.2-Forge-1.18.jar

### Log Output

```shell
[Fatal] Failed to start the minecraft servernet.minecraftforge.fml.LoadingFailedException: Loading errors encountered: BetterF3 (betterf3) encountered an error during the common_setup event phase?7java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER] at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:235) ~[fmlcore-1.18.1-39.0.10.jar%23156!:?] at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:200) ~[fmlcore-1.18.1-39.0.10.jar%23156!:?] at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:200) ~[fmlcore-1.18.1-39.0.10.jar%23156!:?] at net.minecraftforge.fml.ModLoader.lambda$loadMods$14(ModLoader.java:183) ~[fmlcore-1.18.1-39.0.10.jar%23156!:?] at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:183) ~[fmlcore-1.18.1-39.0.10.jar%23156!:?] at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:47) ~[forge-1.18.1-39.0.10-universal.jar%23159!:?] at net.minecraft.server.Main.main(Main.java:104) ~[server-1.18.1-20211210.034407-srg.jar%23155!:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.18.1-39.0.10.jar%2323!:?] at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?].
```

**Comment by TreyRuffy** [comment]
Do you have any other mods?

**Comment by TreyRuffy** [comment]
Wait, this mod isn't supposed to be run on a server. It is a client side only mod and will always error if run on a server.

**Comment by Sunekaer** [comment]
Yes this is a client-side only mod, but many people dont know that and will see their servers crash.
Which is why you often will see something like this https://github.com/nanite/Simple-Discord-Rich-Presence/blob/19bc78dc1eeae0711fa96ee4a4b59e32408cbd23/src/main/java/com/sunekaer/mods/sdrp/SDRP.java#L37-L43 
Then the mod loads on server but none of the code does

**Comment by TreyRuffy** [comment]
I understand, so this is less of a big report and more of a feature request. I'll implement this when I get the chance.

**Comment by sandalle** [comment]
> Yes this is a client-side only mod, but many people dont know that and will see their servers crash. Which is why you often will see something like this https://github.com/nanite/Simple-Discord-Rich-Presence/blob/19bc78dc1eeae0711fa96ee4a4b59e32408cbd23/src/main/java/com/sunekaer/mods/sdrp/SDRP.java#L37-L43 Then the mod loads on server but none of the code does

To add to this point, if your client mods and server mod lists don't match, FML will complain (and show your users) that the client and server disagree.
So mods should still register on dedicated servers (dist/side DEDICATED_SERVER), then do nothing more.

**Comment by sandalle** [comment]
Just FYI in case you need it:
See https://docs.minecraftforge.net/en/1.20.x/concepts/sides/ for how to do it properly:
* Your mods are expected to always load, regardless of if they are loaded on the client or the server. For one-sided mods, this means that they must still run on the opposite physical side.

**Comment by TreyRuffy** [comment]
Those mods are not official BetterF3 mods. BetterF3 already includes this check and can be downloaded from https://modrinth.com/mod/betterf3

**Comment by sandalle** [comment]
> Those mods are not official BetterF3 mods. BetterF3 already includes this check and can be downloaded from https://modrinth.com/mod/betterf3

Thanks! I apparently had the wrong "Better F3" mod installed (my original search in Curse Forge had found https://www.curseforge.com/minecraft/mc-mods/better-f3 instead of https://www.curseforge.com/minecraft/mc-mods/betterf3 ), I've now swapped to this one in my modpack and it works as expected. :)

I'm so sorry for the extra noise and thank you. :)
