### ISSUE TITLE
[Bug]: Slight delay in f3 menu when mod is disabled but animations are not

### ISSUE THREAD

**Issue by Skeithh** [cominixo/BetterF3#65]
### Describe the Bug

A friend of mine found that despite having the mod disabled in modmenu, they still received a delay in opening/closing f3. This got fixed when they set "enable animations" to "no", which seems to mean that the mod continues trying to function even though its set to disabled.

### Steps to Reproduce

1. Have animations on
2. Disable the mod
3. press F3 on/off, see a half a second delay or so
4. Turn animations off
5. press F3 on/off, see how there is no delay

### Expected Behavior

For the mod to basically set all options to "off" state when you disable the mod, or for it to no longer apply its changes at all if it has been disabled.

### Modloader Type

Fabric

### Modloader Version

0.12.12

### Mod Version

v1.2.2

**Comment by TreyRuffy** [comment]
Closing in favor of #66
