### ISSUE TITLE
[Feature]: Add a configurable line count value to separator module

### ISSUE THREAD

**Issue by TheAntVenom** [cominixo/BetterF3#68]
### Describe the Request

Allow us to specify the amount of lines that a given separator... separates.

Presently, if I want to do more than 1 at a time, I have to add them one at a time.

**Comment by TreyRuffy** [comment]
I don't know why I never thought of this before but I will push a commit soon to add this!

**Comment by TreyRuffy** [comment]
I added to the commit 3 days ago. You can access the file from the actions tab or wait for the next release!
