### ISSUE TITLE
[Bug]: pressing f3 crashes game

### ISSUE THREAD

**Issue by Dandyyyy** [cominixo/BetterF3#71]
### Describe the Bug

whenever I open a world and try to press f3 after configuring my settings, it immediately closes the world and crashes the game, sending me a crash report full of nothing.

### Steps to Reproduce

-configure settings in a way other than default
-open a world, may have to do with shaders being active
-press f3

### Expected Behavior

the f3 menu is supposed to open instead of crashing.

### Screenshots

![crash copy](https://user-images.githubusercontent.com/101959920/159146943-abc1a312-53c7-40b4-9252-b7aa178db36d.png)

### Modloader Type

Fabric

### Modloader Version

1.18.2

### Mod Version

1.2.2

### Additional Context

might have to do with fabric 1.18.2 conflicting with betterf3 1.18.

**Comment by cominixo** [comment]
Update to 1.2.3.
