### ISSUE TITLE
[Bug]: GUI Scale: Auto means F3 menu cut off (FORGE)

### ISSUE THREAD

**Issue by TheJessaChannel** [cominixo/BetterF3#73]
### Describe the Bug

Please add a config option for font scale. You have mentioned it before in a couple of closed issues, but I do not see the option in the config for fabric. Thanks.

### Steps to Reproduce

n/a

### Expected Behavior

n/a

### Modloader Type

Minecraft Forge

### Modloader Version

36.2.33

### Mod Version

1.1.3

**Comment by TreyRuffy** [comment]
There is an option if you press F3 + M and head into general options.
