### ISSUE TITLE
[Bug] the Shader option under grapics doesnt show

### ISSUE THREAD

**Issue by SylisMC** [cominixo/BetterF3#8]
**Versions**

- Fabric-api-0.28.4+1.16
- Optifabric-1.8.13
- OptiFine_1.16.4_HD_U_G5
- BetterF3 - 1.1.1

**Discription**

I've tried it with 3 different shader packs and it won't update for some reason
![image](https://user-images.githubusercontent.com/19602662/103390620-75d72e00-4ae3-11eb-92ca-4444c01c3384.png)

**Comment by cominixo** [comment]
Oh my bad on that, shouldn't be an option as it's unused by Minecraft, it's not from Optifine.

**Comment by SylisMC** [comment]
rgr that! awesome mod btw
