### ISSUE TITLE
[Feature]: Make Mod for Forge 1.8.9

### ISSUE THREAD

**Issue by randomsnippets** [cominixo/BetterF3#82]
### Describe the Request

Ive been using this mod for a long time now and its great but, 1.8.9 is the native version of Hypixel and many other servers and it would be very nice to get the Mod fotr this specific Version.

**Comment by TreyRuffy** [comment]
I have no plans to make a 1.8.9 mod. Frankly, there is no reason to still be on that version and there are a lot of other alternatives.
