### ISSUE TITLE
[Bug]: Some strings are not translated

### ISSUE THREAD

**Issue by WakefulSpect** [cominixo/BetterF3#83]
### Describe the Bug

The strings shown below are not in Japanese and do not exist in Crowdin.

> Reset Settings 
> "Reset".
> 
> Setting Yes/No 
> "Yes" "No"
> 
> Save Settings 
> "Save Changes".
> 
> Tab to cancel unsaved settings 
> "Cancel & Discard Changes"
> 
> Player Coordinates 
> "Player coords".
> 
> Warning when canceling unsaved settings 
> "Changes Not Saved".
> 
> Warning text when canceling unsaved settings 
> "Are you sure..."
> 
> Server Tick 
> "Server tick".
> 
> Unknown module name 
> "Invaild Value!"
> 
> Error 
> "Error!"
> 
> Failure of translation
> "text.betterf3.line.blank" 
> "text.betterf3.line.blank2"

### Steps to Reproduce

(As an example, here is a bug in the translation of "Reset".)

1. Open Better F3 settings.
2. Select the General Settings tab.
3. Untranslated string "Reset" appears from English.

### Expected Behavior

The correctly translated string is displayed.
Or, the corresponding string is submitted to Crowdin's translation request.

### Screenshots

![2022-06-03_13 21 01](https://user-images.githubusercontent.com/76470785/171785569-16e5c4cb-14f8-4866-b3e0-974009b18cb2.png)

### Modloader Type

Fabric

### Modloader Version

0.48.0

### Mod Version

1.2.5

**Comment by TreyRuffy** [comment]
Just quickly looking at this, it looks like the issue is Cloth Config (https://github.com/shedaniel/cloth-config) being untranslated for Japanese. I will try to look through the program and see if I can fix translation issues outside of Cloth Config.
