### ISSUE TITLE
[Feature]: Disable Gizmo

### ISSUE THREAD

**Issue by BeeFox-sys** [cominixo/BetterF3#88]
### Describe the Request

An option to disable the gizmo that replaces the cursor when f3 is enabled

### Modloader Type

Fabric

**Comment by TreyRuffy** [comment]
I just looked into the Minecraft code and I am not sure if there is a way to mixin to disable the f3 crosshair without creating incompatibilities with other mods which modify the crosshair. It might be smarter to use another mod in order to change this setting, but I will keep looking.

**Comment by Monorange** [comment]
https://modrinth.com/mod/nogizmo

gotcha

**Comment by TreyRuffy** [comment]
Added in #110
