### ISSUE TITLE
[Suggestion] Option to automatically open pie & fps/tps charts

### ISSUE THREAD

**Issue by MithicSpirit** [cominixo/BetterF3#9]
There should be a way to make the pie graph or fps/tps charts be "locked on" so that I don't have to hold down shift or alt every time. This could either be done the Optifine way, where you have an option that just makes them always be on, or have it act as a toggle, where after you do shift+f3 then the pie graph is always on in the f3 screen, then you can do shift+f3 again to have it be disabled again.

**Comment by cominixo** [comment]
I'm not sure what you mean, that's how it already works in vanilla, pressing F3 + Shift keeps the pie graph all the time until F3 is closed again.

**Comment by MithicSpirit** [comment]
Oh sorry I meant that when I close F3 the pie graph goes away but if I reopen the F3 menu, even without holding down shift, the pie graph should come back.
