### ISSUE TITLE
[Bug]: crashing on f3 open with canvas render in version 1.19 (quilt)

### ISSUE THREAD

**Issue by unmellow** [cominixo/BetterF3#90]
### Describe the Bug

literally
 the title not sure if settings effect it but I have a long list of mods

Mods:
  [✔️] 3dskinlayers-fabric-1.4.7-mc1.19
  [✔️] architectury-5.7.27-fabric
  [✔️] BetterF3-1.3.1-Fabric-1.19
  [✔️] bettermounthud-1.1.4
  [✔️] borderless-mining-1.1.4+1.19
  [✔️] c2me-fabric-mc1.19-0.2.0+alpha.8.0
  [✔️] canvas-fabric-mc119-1.0.2374.jar (disabled)
  [✔️] charmonium-fabric-1.19-4.1.0
  [✔️] Chunky-1.2.202
  [✔️] clickthrough-1.19-fabric0.53.3-0.4
  [✔️] cloth-config-7.0.72-fabric
  [✔️] CullLessLeaves-1.0.2
  [✔️] dashloader-4.0.0+1.19
  [✔️] debugify-2.1.0-fabric-1.19
  [✔️] dynamic-fps-2.2.0
  [✔️] emotecraft-for-MC1.19-2.1.3-SNAPSHOT-build.31-fabric
  [✔️] enhancedblockentities-0.7+1.19
  [✔️] entityculling-fabric-1.5.2-mc1.19
  [✔️] extrasounds-2.3.1+1.19
  [✔️] fallingleaves-1.12.1+1.19
  [✔️] ferritecore-5.0.0-fabric
  [✔️] journeymap-1.19-5.8.5rc2-fabric
  [✔️] krypton-0.2.0
  [✔️] language-reload-1.3.1
  [✔️] lazydfu-0.1.3
  [✔️] lithium-fabric-mc1.19-0.8.0
  [✔️] memoryleakfix-1.19-0.4.1
  [✔️] modmenu-4.0.0
  [✔️] notenoughanimations-fabric-1.6.0-mc1.19
  [✔️] notenoughcrashes-4.1.6+1.19-fabric
  [✔️] PresenceFootsteps-1.6.0
  [✔️] qfapi-2.0.0-alpha.3_qsl-2.0.0-beta.2_fapi-0.55.3_mc-1.19
  [✔️] raised-fabric-1.19-pre1-1.1.1
  [✔️] RoughlyEnoughItems-9.0.491
  [✔️] servercore-1.3.0-1.19
  [✔️] smoothboot-fabric-1.19-1.7.1
  [✔️] starlight-1.1.1+fabric.ae22326
  [✔️] stendhal-1.3.3-1.19
  [✔️] viafabric-0.4.7+5-main
  [✔️] visuality-0.5.0
  [✔️] vmp-fabric-mc1.19-0.2.0+beta.4.0-all
  
  and my game only crashes when betterf3 and canvas are both enabled

### Steps to Reproduce

download better f3 and canvas install both mods and all their dependencies
with quilt
launch minecraft
and enter a game press f3 and the game crashes

### Expected Behavior

as similar to how it works in 1.18.2
with fabric i would like to see information about canvas
in my f3 menu and not have my game crash

(sorry if i sound passive aggressive Don't know how else to describe the expected behavior)

### Modloader Type

Fabric

### Modloader Version

quilt 0.17.0

### Mod Version

1.3.1

### Log Output

```shell
https://gist.github.com/unmellow/f0d599902bec5471f3859c47586213ed
```

### Additional Context

I ran it with my other mods because i was to lazy to disable them if you need me to generate logs with only canvas and better f3 lmk

**Comment by TreyRuffy** [comment]
Fixed in the latest commit
