### ISSUE TITLE
[Feature]: Customize Text / Code

### ISSUE THREAD

**Issue by Monorange** [cominixo/BetterF3#91]
### Describe the Request

An Option to change the text and code, for example the coordinates code is "%.3f  %.5f %.5f" , so an ability to change that. like the minihud mod does:

### Screenshots

![image](https://user-images.githubusercontent.com/100101443/174463498-2fad5832-2c65-4109-a66c-3acda318e313.png)

**Comment by Monorange** [comment]
format*

**Comment by TreyRuffy** [comment]
Closing in favor of #55
