### ISSUE TITLE
Background applies to newlines, and is not aligned to text

### ISSUE THREAD

**Issue by jan-Sanku** [cominixo/BetterF3#92]
![image](https://user-images.githubusercontent.com/56739341/174482462-8a5f72f6-4a45-47f6-b2ed-e8963c685ddc.png)

As opposed to what can be seen in the official screenshots, it seems that all empty lines between debug lines will have a stripe of background, presumably because it treats CRLF (newline) as a visible character.

Additionally, the background is off by at least 1 pixel relative to the text. You can see it on the left side of the screenshot if you look closely, the leftmost pixel of the text is without background.

I'm not sure if this is a bug, but it happens to me regardless of settings or other mods as long as there is empty space between modules.

**Comment by Braite1** [comment]
This is a very annoying issue
