### ISSUE TITLE
[Bug]: Left Module background Cut off slightly

### ISSUE THREAD

**Issue by Braite1** [cominixo/BetterF3#94]
### Describe the Bug

The background for any Left Module is cut off by a few pixels, unlike vanilla. However the Right side is unaffected
![2022-07-02_13 24 06](https://user-images.githubusercontent.com/104676867/176984988-bb04f5bf-2d81-47ac-8e33-d03f7bbe3740.png)
![2022-07-02_13 26 46](https://user-images.githubusercontent.com/104676867/176985037-f361d64d-e739-42a4-b93d-fc16ec92ec31.png)
.

### Steps to Reproduce

Simply Open the F3 Menu

### Expected Behavior

Both sides (left & right) would look the same

### Screenshots

These images are edited to be what it Should look like
![2022-07-02_13 24 06 - Copy](https://user-images.githubusercontent.com/104676867/176985234-f3cbb3fe-6aae-4ee1-a818-92d0c41c4b19.png)
![2022-07-02_13 31 37 - Copy](https://user-images.githubusercontent.com/104676867/176985244-050ea453-0297-4968-9eb1-0f73000e7763.png)
:

### Modloader Type

Fabric

### Modloader Version

0.11.0

### Mod Version

1.2.5 But it still happens in the latest version

### Additional Context

As a side note: there also seems to be 2 added pixels on the separator
![2022-07-02_13 31 37](https://user-images.githubusercontent.com/104676867/176985107-9df8dc78-95af-4eb7-925e-54005fea8e9b.png)
.

**Comment by TreyRuffy** [comment]
Does this still happen in 1.3.2?

**Comment by Braite1** [comment]
> Does this still happen in 1.3.2?

Yes, it still occurs
